// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	CreateAddress(ctx context.Context, arg CreateAddressParams) (Address, error)
	CreateApiKey(ctx context.Context, arg CreateApiKeyParams) (ApiKey, error)
	CreateClient(ctx context.Context, arg CreateClientParams) (Client, error)
	CreateShipmentStatusLog(ctx context.Context, arg CreateShipmentStatusLogParams) (ShipmentStatusLog, error)
	CreateShipper(ctx context.Context, arg CreateShipperParams) (Shipper, error)
	DeleteAddress(ctx context.Context, id int64) error
	DeleteApiKey(ctx context.Context, id int64) error
	DeleteClient(ctx context.Context, id int64) error
	DeleteShipment(ctx context.Context, id int64) error
	DeleteShipmentStatusLog(ctx context.Context, id int64) error
	DeleteShipper(ctx context.Context, id int64) error
	GetAddress(ctx context.Context, id int64) (Address, error)
	GetApiKey(ctx context.Context, id int64) (ApiKey, error)
	GetClient(ctx context.Context, id int64) (Client, error)
	GetShipment(ctx context.Context, id int64) (Shipment, error)
	GetShipmentStatusLog(ctx context.Context, id int64) (ShipmentStatusLog, error)
	GetShipper(ctx context.Context, id int64) (Shipper, error)
	ListAddresses(ctx context.Context, arg ListAddressesParams) ([]Address, error)
	ListApiKeys(ctx context.Context, arg ListApiKeysParams) ([]ApiKey, error)
	ListApiKeysByClientID(ctx context.Context, arg ListApiKeysByClientIDParams) ([]ApiKey, error)
	ListClients(ctx context.Context, arg ListClientsParams) ([]Client, error)
	ListLogsByShipmentID(ctx context.Context, shipmentID sql.NullInt64) ([]ShipmentStatusLog, error)
	ListShipmentStatusLogs(ctx context.Context, arg ListShipmentStatusLogsParams) ([]ShipmentStatusLog, error)
	ListShipments(ctx context.Context, arg ListShipmentsParams) ([]Shipment, error)
	ListShipmentsByClient(ctx context.Context, arg ListShipmentsByClientParams) ([]Shipment, error)
	ListShippers(ctx context.Context, arg ListShippersParams) ([]Shipper, error)
	UpdateAddress(ctx context.Context, arg UpdateAddressParams) (Address, error)
	UpdateApiKey(ctx context.Context, arg UpdateApiKeyParams) (ApiKey, error)
	UpdateClient(ctx context.Context, arg UpdateClientParams) (Client, error)
	UpdateShipment(ctx context.Context, arg UpdateShipmentParams) (Shipment, error)
	UpdateShipper(ctx context.Context, arg UpdateShipperParams) (Shipper, error)
}

var _ Querier = (*Queries)(nil)
